"""add share_reactions table

Revision ID: 6f91cb3162fc
Revises: 83b1aa8cb15a
Create Date: 2026-03-03 20:11:27.170222

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f91cb3162fc"
down_revision: str | Sequence[str] | None = "83b1aa8cb15a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "share_reactions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("share_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("emoji", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["share_id"], ["document_shares.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_share_reactions_share_user_emoji",
        "share_reactions",
        ["share_id", "user_id", "emoji"],
        unique=True,
    )
    op.create_index(
        op.f("ix_share_reactions_share_id"), "share_reactions", ["share_id"], unique=False
    )
    op.create_index(
        op.f("ix_share_reactions_user_id"), "share_reactions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_share_reactions_user_id"), table_name="share_reactions")
    op.drop_index(op.f("ix_share_reactions_share_id"), table_name="share_reactions")
    op.drop_index("idx_share_reactions_share_user_emoji", table_name="share_reactions")
    op.drop_table("share_reactions")
    # ### end Alembic commands ###
