"""add refresh_tokens table for dual-token authentication

Revision ID: 87ab147f0fb1
Revises: 0014_content_markdown
Create Date: 2026-03-01 16:12:48.789372

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87ab147f0fb1"
down_revision: str | Sequence[str] | None = "0014_content_markdown"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("device_fingerprint", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("device_name", sa.String(length=100), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_refresh_tokens_expires", "refresh_tokens", ["expires_at"], unique=False)
    op.create_index(
        "idx_refresh_tokens_user_device",
        "refresh_tokens",
        ["user_id", "device_fingerprint"],
        unique=False,
    )
    op.create_index(
        "idx_refresh_tokens_user_revoked", "refresh_tokens", ["user_id", "is_revoked"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_is_revoked"), "refresh_tokens", ["is_revoked"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.drop_table("admin_audit_logs")
    op.drop_table("export_jobs")
    op.drop_table("admin_users")
    op.alter_column(
        "api_usage",
        "is_byok",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "api_usage",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "bookmarks",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "comment_reactions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_reactions_comment_id"), table_name="comment_reactions")
    op.drop_index(op.f("ix_reactions_user_id"), table_name="comment_reactions")
    op.create_index(
        op.f("ix_comment_reactions_comment_id"), "comment_reactions", ["comment_id"], unique=False
    )
    op.create_index(
        op.f("ix_comment_reactions_user_id"), "comment_reactions", ["user_id"], unique=False
    )
    op.alter_column(
        "comments",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "comments",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_document_shares_is_published"), "document_shares", ["is_published"], unique=False
    )
    op.alter_column(
        "files",
        "position",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "forks",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "messages",
        "is_byok",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "telemetry_events",
        "event_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.alter_column(
        "telemetry_events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_telemetry_events_created"), table_name="telemetry_events")
    op.drop_index(op.f("idx_telemetry_events_type"), table_name="telemetry_events")
    op.drop_index(op.f("idx_telemetry_events_user_id"), table_name="telemetry_events")
    op.create_index("idx_telemetry_created", "telemetry_events", ["created_at"], unique=False)
    op.create_index(
        "idx_telemetry_user_type", "telemetry_events", ["user_id", "event_type"], unique=False
    )
    op.create_index(
        op.f("ix_telemetry_events_created_at"), "telemetry_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_telemetry_events_event_type"), "telemetry_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_telemetry_events_user_id"), "telemetry_events", ["user_id"], unique=False
    )
    op.alter_column(
        "user_telemetry_settings",
        "product_improvement_enabled",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_telemetry_settings",
        "collect_edit_feedback",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_telemetry_settings",
        "collect_chat_feedback",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_telemetry_settings",
        "collect_autocomplete_stats",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_telemetry_settings",
        "collect_usage_stats",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_telemetry_settings",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_users_stripe_customer"), table_name="users")
    op.drop_constraint(op.f("uq_users_stripe_subscription"), "users", type_="unique")
    op.drop_column("users", "claude_oauth_token_encrypted")
    op.drop_column("users", "plan_start_date")
    op.drop_column("users", "plan_type")
    op.drop_column("users", "storage_used_bytes")
    op.drop_column("users", "stripe_subscription_id")
    op.drop_column("users", "anthropic_api_key_encrypted")
    op.drop_column("users", "preferred_model")
    op.drop_column("users", "plan_end_date")
    op.drop_column("users", "stripe_customer_id")
    op.drop_column("users", "image_storage_used_bytes")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "image_storage_used_bytes",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column("stripe_customer_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "plan_end_date", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column("preferred_model", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("anthropic_api_key_encrypted", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "stripe_subscription_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "storage_used_bytes",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "plan_type",
            sa.VARCHAR(length=10),
            server_default=sa.text("'free'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "plan_start_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column("claude_oauth_token_encrypted", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_unique_constraint(
        op.f("uq_users_stripe_subscription"),
        "users",
        ["stripe_subscription_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("idx_users_stripe_customer"), "users", ["stripe_customer_id"], unique=True)
    op.alter_column(
        "user_telemetry_settings",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "user_telemetry_settings",
        "collect_usage_stats",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_telemetry_settings",
        "collect_autocomplete_stats",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_telemetry_settings",
        "collect_chat_feedback",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_telemetry_settings",
        "collect_edit_feedback",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_telemetry_settings",
        "product_improvement_enabled",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.drop_index(op.f("ix_telemetry_events_user_id"), table_name="telemetry_events")
    op.drop_index(op.f("ix_telemetry_events_event_type"), table_name="telemetry_events")
    op.drop_index(op.f("ix_telemetry_events_created_at"), table_name="telemetry_events")
    op.drop_index("idx_telemetry_user_type", table_name="telemetry_events")
    op.drop_index("idx_telemetry_created", table_name="telemetry_events")
    op.create_index(
        op.f("idx_telemetry_events_user_id"), "telemetry_events", ["user_id"], unique=False
    )
    op.create_index(
        op.f("idx_telemetry_events_type"), "telemetry_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("idx_telemetry_events_created"), "telemetry_events", ["created_at"], unique=False
    )
    op.alter_column(
        "telemetry_events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "telemetry_events",
        "event_data",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "messages",
        "is_byok",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "forks",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "files",
        "position",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.drop_index(op.f("ix_document_shares_is_published"), table_name="document_shares")
    op.alter_column(
        "comments",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "comments",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_comment_reactions_user_id"), table_name="comment_reactions")
    op.drop_index(op.f("ix_comment_reactions_comment_id"), table_name="comment_reactions")
    op.create_index(op.f("ix_reactions_user_id"), "comment_reactions", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_reactions_comment_id"), "comment_reactions", ["comment_id"], unique=False
    )
    op.alter_column(
        "comment_reactions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "bookmarks",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "api_usage",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "api_usage",
        "is_byok",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.create_table(
        "admin_users",
        sa.Column("id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("hashed_password", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "role",
            sa.VARCHAR(length=20),
            server_default=sa.text("'viewer'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_login_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("admin_users_pkey")),
        sa.UniqueConstraint(
            "email",
            name=op.f("admin_users_email_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "export_jobs",
        sa.Column("id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("admin_user_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("export_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("format", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            sa.VARCHAR(length=20),
            server_default=sa.text("'pending'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("file_path", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("file_size_bytes", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column("record_count", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "completed_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("export_jobs_pkey")),
    )
    op.create_table(
        "admin_audit_logs",
        sa.Column("id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("admin_user_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("action", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("target_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("target_id", sa.VARCHAR(length=36), autoincrement=False, nullable=True),
        sa.Column("details", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ip_address", sa.VARCHAR(length=45), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("admin_audit_logs_pkey")),
    )
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_is_revoked"), table_name="refresh_tokens")
    op.drop_index("idx_refresh_tokens_user_revoked", table_name="refresh_tokens")
    op.drop_index("idx_refresh_tokens_user_device", table_name="refresh_tokens")
    op.drop_index("idx_refresh_tokens_expires", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    # ### end Alembic commands ###
