"""remove unused columns: file_versions.diff, conversation_data_files.claude_* and content_hash

Revision ID: b8357ee86310
Revises: 0020_avatar_frame
Create Date: 2026-03-09 12:52:16.851060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8357ee86310'
down_revision: Union[str, Sequence[str], None] = '0020_avatar_frame'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_data_files', 'claude_upload_status')
    op.drop_column('conversation_data_files', 'claude_file_id')
    op.drop_column('conversation_data_files', 'content_hash')
    op.drop_column('conversation_data_files', 'claude_upload_error')
    op.drop_column('file_versions', 'diff')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_versions', sa.Column('diff', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('conversation_data_files', sa.Column('claude_upload_error', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('conversation_data_files', sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('conversation_data_files', sa.Column('claude_file_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('conversation_data_files', sa.Column('claude_upload_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
