// =============================================================================
// File Types
// =============================================================================

export interface FileItem {
  id: string;
  name: string;
  content: string;
  createdAt: string;
  updatedAt: string;
}

// =============================================================================
// Edit Operation Types (unified from multiple sources)
// =============================================================================

/**
 * Edit operation from AI agent
 * Used for applying changes to files via str_replace, insert, or replace_all
 */
export interface EditOperation {
  /** Type of edit operation */
  type: "str_replace" | "insert" | "replace_all";
  /** ID of the file being edited */
  file_id: string;
  /** Name of the file being edited */
  file_name: string;
  /** Whether the operation was successful */
  success: boolean;
  /** Error message if operation failed */
  error?: string;
  /** Original string to replace (for str_replace) */
  old_str?: string;
  /** New string to insert (for str_replace and insert) */
  new_str?: string;
  /** Line number to insert at (for insert) */
  insert_line?: number;
  /** Complete new content (for replace_all) */
  new_content?: string;
  /** Plain text version of old_str for diff view matching (generated by backend) */
  search_text?: string;
}

// =============================================================================
// Chat Types
// =============================================================================

export interface ToolCall {
  name: string;
  toolId?: string;
  input: string;
  output: string | null;
  success: boolean | null;
}

/** Context item attached to a user message (from "Ask in Chat" feature) */
export type MessageContextItem =
  | {
      type: "selection";
      text: string;
    }
  | {
      type: "image";
      src: string;
      alt?: string;
      base64?: string;      // Base64 encoded image data (without data:... prefix)
      mediaType?: string;   // MIME type (image/jpeg, image/png, etc.)
    };

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  fileIds?: string[];
  createdAt: string;
  isStreaming?: boolean;
  // User message specific fields
  contexts?: MessageContextItem[] | null;
  // AI response specific fields
  thinking?: string | null;
  toolCalls?: ToolCall[] | null;
  edits?: EditOperation[] | null;
  model?: string | null;
}

export interface Conversation {
  id: string;
  fileId: string | null;
  messages: ChatMessage[];
  createdAt: string;
  isLoaded?: boolean;
}

// =============================================================================
// Version Types
// =============================================================================

export interface FileVersion {
  id: string;
  fileId: string;
  content: string;
  diff?: string;
  editType?: string;
  summary?: string;
  createdAt: string;
}

// =============================================================================
// Editor Types
// =============================================================================

export interface Selection {
  from: number;
  to: number;
  text: string;
}

// =============================================================================
// API Types
// =============================================================================

export interface ApiError {
  detail: string;
  status?: number;
}

export interface StreamEvent {
  type: "text" | "tool_start" | "tool_end" | "error";
  content?: string;
  tool?: string;
  input?: string;
  output?: string;
}

// =============================================================================
// Quick Edit Types
// =============================================================================

export type QuickEditAction =
  | "fix-grammar"
  | "improve"
  | "simplify"
  | "expand"
  | "shorten"
  | "professional"
  | "casual"
  | "translate-en"
  | "translate-zh";

export interface QuickEditOption {
  id: QuickEditAction;
  label: string;
  icon: React.ReactNode;
}

// =============================================================================
// Search Types
// =============================================================================

export interface SearchResult {
  id: string;
  content: string;
  metadata: {
    file_id: string;
    chunk_index: number;
    start?: number;  // Position in original document (for highlighting)
    end?: number;    // Position in original document (for highlighting)
    [key: string]: unknown;
  };
  distance?: number;
}
