//! Markdown -> PDF native save hook.
//!
//! PDF layout is generated by the local Python sidecar with PyMuPDF. Tauri only
//! writes the returned bytes to the user-selected path.

use std::fs::OpenOptions;
use std::io::Write;
use std::path::Path;

pub fn save_window_pdf(
    _window: tauri::WebviewWindow,
    target_path: String,
    bytes: Vec<u8>,
) -> Result<(), String> {
    if target_path.trim().is_empty() {
        return Err("PDF target path is empty".into());
    }
    if !bytes.starts_with(b"%PDF-") {
        return Err("PDF payload is invalid".into());
    }

    write_new_pdf(Path::new(&target_path), &bytes)
}

fn write_new_pdf(path: &Path, bytes: &[u8]) -> Result<(), String> {
    let is_pdf = path
        .extension()
        .and_then(|extension| extension.to_str())
        .is_some_and(|extension| extension.eq_ignore_ascii_case("pdf"));
    if !is_pdf {
        return Err("PDF target must use the .pdf extension".into());
    }

    // `create_new` is intentionally no-clobber. Page export must create a new
    // file, never overwrite an Attachment or legacy recovery evidence.
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)
        .map_err(|e| format!("create PDF target: {e}"))?;
    file.write_all(bytes).map_err(|e| format!("write PDF: {e}"))
}

#[cfg(test)]
mod tests {
    use super::write_new_pdf;
    use std::fs;
    use std::path::PathBuf;
    use std::sync::atomic::{AtomicU64, Ordering};

    fn temporary_directory(label: &str) -> PathBuf {
        static COUNTER: AtomicU64 = AtomicU64::new(0);
        let path = std::env::temp_dir().join(format!(
            "doxmind-pdf-save-{}-{}-{label}",
            std::process::id(),
            COUNTER.fetch_add(1, Ordering::Relaxed)
        ));
        fs::create_dir(&path).expect("create temp directory");
        path
    }

    #[test]
    fn writes_a_new_pdf_target() {
        let directory = temporary_directory("new");
        let target = directory.join("Page.PDF");

        write_new_pdf(&target, b"%PDF-1.7\npage").expect("write new PDF");

        assert_eq!(fs::read(&target).expect("read PDF"), b"%PDF-1.7\npage");
        fs::remove_dir_all(directory).expect("remove temp directory");
    }

    #[test]
    fn existing_pdf_is_not_overwritten_or_touched() {
        let directory = temporary_directory("existing");
        let target = directory.join("Evidence.pdf");
        fs::write(&target, b"original").expect("seed target");
        let before = fs::metadata(&target).expect("metadata");

        let error = write_new_pdf(&target, b"%PDF-1.7\nreplacement").expect_err("reject");

        assert!(error.contains("create PDF target"));
        assert_eq!(fs::read(&target).expect("read target"), b"original");
        let after = fs::metadata(&target).expect("metadata");
        assert_eq!(
            after.modified().expect("mtime"),
            before.modified().expect("mtime")
        );
        fs::remove_dir_all(directory).expect("remove temp directory");
    }

    #[test]
    fn non_pdf_and_recovery_evidence_targets_are_rejected_without_writing() {
        let directory = temporary_directory("invalid");
        for name in [
            ".Evidence.doxmind",
            ".Evidence.doxmind.bak",
            ".Evidence.doxmind.lock",
            "Page.xlsx",
        ] {
            let target = directory.join(name);
            let error = write_new_pdf(&target, b"%PDF-1.7\npage").expect_err("reject");
            assert!(error.contains(".pdf extension"));
            assert!(!target.exists());
        }
        fs::remove_dir_all(directory).expect("remove temp directory");
    }
}
