//! Markdown -> PDF native save hook.
//!
//! PDF layout is generated by the local Python sidecar with PyMuPDF. Tauri only
//! writes the returned bytes to the user-selected path.

use std::fs;
use std::path::Path;

pub fn save_window_pdf(
    _window: tauri::WebviewWindow,
    target_path: String,
    bytes: Vec<u8>,
) -> Result<(), String> {
    if target_path.trim().is_empty() {
        return Err("PDF target path is empty".into());
    }
    if !bytes.starts_with(b"%PDF-") {
        return Err("PDF payload is invalid".into());
    }

    let path = Path::new(&target_path);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("create parent directory: {e}"))?;
    }
    fs::write(path, bytes).map_err(|e| format!("write PDF: {e}"))
}
